# Generated by Django 4.2.1 on 2025-10-22 06:25

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default='<p></p>', verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Markaz nomi')),
                ('slug', models.SlugField(help_text='Sayt URL uchun unikal nom', unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name="Aktiv (To'lov muddati o'tmagan)")),
            ],
            options={
                'verbose_name': "O'quv Markazi",
                'verbose_name_plural': "O'quv Markazlari",
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('course_type', models.CharField(choices=[('online', 'Online Kurs'), ('offline', "Offline Kurs (An'anaviy)")], default='online', max_length=10, verbose_name='Kurs turi')),
                ('online_lesson_flow', models.CharField(choices=[('self_paced', "Ixtiyoriy (Talaba o'zi boshqaradi)"), ('scheduled', 'Jadval asosida (Muddatli/Vaqtli)')], default='self_paced', help_text="'Ixtiyoriy'da tezlik talabaga bog'liq, 'Jadval asosida'da vaqt cheklangan.", max_length=10, verbose_name='Online darslar turi')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Pullik kurs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kurs narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Mock.center', verbose_name='Tegishli Markaz')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Mock.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Kurs Moduli',
                'verbose_name_plural': 'Kurs Modullari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('is_subject_exam', models.BooleanField(default=False, help_text="Agar bu imtihon to'liq SAT sinovi emas, balki biror mavzu bo'yicha test bo'lsa", verbose_name='Mavzu testi')),
                ('passing_percentage', models.PositiveIntegerField(default=60, help_text="O'quvchi keyingi darsga o'tishi uchun to'plashi kerak bo'lgan minimal foiz (0-100)", verbose_name="O'tish foizi (%)")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Pullik imtihon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Mock.center', verbose_name='Tegishli Markaz')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExamPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'mda)")),
                ('includes_flashcards', models.BooleanField(default=False, verbose_name="Flashcardlar to'plamini o'z ichiga oladimi?")),
                ('exam_credits', models.PositiveIntegerField(verbose_name='Beriladigan imtihonlar soni (kredit)')),
                ('solution_view_credits_on_purchase', models.PositiveIntegerField(default=0, verbose_name='Beriladigan yechimlar soni (kredit)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_packages', to='Mock.center', verbose_name="O'quv Markazi")),
                ('exams', models.ManyToManyField(blank=True, related_name='packages', to='Mock.exam', verbose_name='Paketdagi imtihonlar')),
            ],
            options={
                'verbose_name': 'Imtihon paketi',
                'verbose_name_plural': 'Imtihon paketlari',
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Qiyin darajali Writing, Yengil darajali Math-Calc.', max_length=150, unique=True, verbose_name='Bo‘lim nomi')),
                ('section_type', models.CharField(choices=[('subject_test', 'Mavzu testi'), ('read_write_m1', 'Reading'), ('read_write_m2', 'Writing and Language'), ('math_no_calc', 'Math (No Calculator)'), ('math_calc', 'Math (Calculator)')], max_length=30, verbose_name='Bo‘lim turi')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Davomiyligi (minut)')),
                ('max_questions', models.PositiveIntegerField(verbose_name='Maksimal savollar soni')),
                ('min_difficulty', models.FloatField(blank=True, null=True, verbose_name='Minimal qiyinlik (IRT)')),
                ('max_difficulty', models.FloatField(blank=True, null=True, verbose_name='Maksimal qiyinlik (IRT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sections', to='Mock.center', verbose_name='Tegishli Markaz')),
            ],
            options={
                'verbose_name': 'Bo‘lim shabloni',
                'verbose_name_plural': 'Bo‘lim shablonlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('word', "So'z/Ibora"), ('formula', 'Formula')], default='word', max_length=20, verbose_name='Kontent turi')),
                ('english_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Inglizcha kontent')),
                ('uzbek_meaning', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="O'zbekcha ma'nosi")),
                ('context_sentence', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Kontekst (gap)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Flashcard (lug'at)",
                'verbose_name_plural': "Flashcardlar (lug'atlar)",
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Mock.coursemodule', verbose_name='Modul')),
                ('related_exam', models.OneToOneField(blank=True, help_text="Bu darsga test biriktirilishi shart emas. Agar biriktirilsa, keyingi darsga o'tish uchun talab etiladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='Mock.exam', verbose_name='Mavzu testi')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['module__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Matn sarlavhasi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matn (Passage)',
                'verbose_name_plural': 'Matnlar (Passages)',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promo kod')),
                ('discount_type', models.CharField(choices=[('percentage', 'Foiz'), ('fixed', 'Fiks summa')], default='percentage', max_length=20, verbose_name='Chegirma turi')),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Foiz chegirmasi uchun, masalan, 10% uchun 10 kiriting', null=True, verbose_name='Chegirma foizi')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Fiks summa chegirmasi uchun, masalan, 50000 so'm", max_digits=10, null=True, verbose_name='Fiks chegirma summasi')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Amal qilish boshlanishi')),
                ('valid_until', models.DateTimeField(verbose_name='Amal qilish tugashi')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Maksimal ishlatishlar soni')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ishlatilganlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='Mock.center', verbose_name="O'quv Markazi")),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default='<p></p>', verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Savol rasmi')),
                ('correct_short_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'g'ri qisqa javob")),
                ('answer_format', models.CharField(choices=[('single', 'Yagona tanlov'), ('multiple', "Ko'p tanlov"), ('short_answer', 'Qisqa javob')], default='single', max_length=20, verbose_name='Javob formati')),
                ('difficulty', models.FloatField(db_index=True, default=0.0, verbose_name='Qiyinlik darajasi (IRT difficulty)')),
                ('discrimination', models.FloatField(default=1.0, verbose_name='Farqlash parametri (IRT discrimination)')),
                ('guessing', models.FloatField(default=0.25, verbose_name='Taxmin parametri (IRT guessing)')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=20, verbose_name='Holati')),
                ('is_calibrated', models.BooleanField(db_index=True, default=False, verbose_name='Kalibrlanganmi?')),
                ('response_count', models.PositiveIntegerField(default=0, verbose_name='Javoblar soni')),
                ('is_solution_free', models.BooleanField(default=False, verbose_name='Yechim bepulmi?')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaschDifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Daraja nomi')),
                ('min_difficulty', models.FloatField(default=-3.0, verbose_name='Minimal qiyinlik')),
                ('max_difficulty', models.FloatField(default=3.0, verbose_name='Maksimal qiyinlik')),
            ],
            options={
                'verbose_name': 'Rasch qiyinlik darajasi',
                'verbose_name_plural': 'Rasch qiyinlik darajalari',
                'ordering': ['min_difficulty'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_card_number', models.CharField(help_text="To'lov qabul qilinadigan plastik karta raqami. Format: 8600 1234 ...", max_length=20)),
                ('payment_card_holder', models.CharField(help_text='Karta egasining ismi va familiyasi. Masalan: ALI VALIYEV', max_length=100)),
                ('manager_phone_number', models.CharField(help_text="To'lovni tezkor tasdiqlash uchun menejer telefon raqami. Format: +998901234567", max_length=20)),
                ('manager_telegram_username', models.CharField(blank=True, help_text="Menejerning telegram username'i (masalan, @menejer_username)", max_length=100)),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Obuna rejasi nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'mda)")),
                ('duration_days', models.PositiveIntegerField(verbose_name='Amal qilish muddati (kunda)')),
                ('includes_flashcards', models.BooleanField(default=False, verbose_name="Flashcardlar to'plamini o'z ichiga oladimi?")),
                ('includes_solution_access', models.BooleanField(default=False, verbose_name="Yechimlarni ko'rishni o'z ichiga oladimi?")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_calibration_threshold', models.PositiveIntegerField(default=30, help_text="Savolning qiyinlik darajasi shu sondagi javoblardan so'ng avtomatik hisoblanadi.", verbose_name='Savolni kalibrovka qilish uchun minimal javoblar soni')),
                ('solutions_enabled', models.BooleanField(default=True, verbose_name='Savol yechimlarini yoqish')),
                ('default_solutions_are_free', models.BooleanField(default=False, help_text="Agar bu yoqilgan bo'lsa, 'Yechim bepulmi?' deb belgilanmagan barcha savollar yechimi pullik bo'ladi.", verbose_name='Standart holatda yechimlar bepulmi?')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teg/Mavzu nomi')),
                ('description', models.TextField(blank=True, help_text="Ushbu teg/mavzu haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Mock.tag', verbose_name='Ota-ona teg (yuqori darajali mavzu)')),
            ],
            options={
                'verbose_name': 'Teg/Mavzu',
                'verbose_name_plural': 'Teglar/Mavzular',
            },
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Tugatilgan')),
                ('final_ebrw_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakuniy EBRW balli')),
                ('final_math_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakuniy Math balli')),
                ('final_total_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakuniy umumiy ball')),
                ('correct_percentage', models.FloatField(default=0.0, verbose_name="To'g'ri javoblar foizi")),
                ('mode', models.CharField(default='exam', max_length=50, verbose_name='Imtihon rejimi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.exam', verbose_name='Imtihon')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi urinishi',
                'verbose_name_plural': 'Foydalanuvchi urinishlari',
            },
        ),
        migrations.CreateModel(
            name='UserAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1, verbose_name='Savol tartibi')),
            ],
            options={
                'verbose_name': 'Urinish savoli tartibi',
                'verbose_name_plural': 'Urinish savollari tartibi',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism (F.I.Sh)")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Elektron pochta')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon raqami')),
                ('role', models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('center_admin', 'Markaz Admini'), ('admin', 'Platforma Super Admini')], default='student', max_length=20, verbose_name='Foydalanuvchi roli')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil rasmi')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name="O'zi haqida")),
                ('ability', models.FloatField(default=0.0, verbose_name='Foydalanuvchi qobiliyati (Rasch)')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='Mock.center', verbose_name="O'quv Markazi")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'teacher'), ('role', 'center_admin'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan Ustoz/Admin')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Boshlangan sana')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sana')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Avtomatik uzaytirish')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.subscriptionplan', verbose_name='Obuna rejasi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi obunasi',
                'verbose_name_plural': 'Foydalanuvchi obunalari',
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_attempts_completed', models.PositiveIntegerField(default=0, verbose_name='Yakunlangan exam mode urinishlari')),
                ('study_attempts_completed', models.PositiveIntegerField(default=0, verbose_name='Yakunlangan study mode urinishlari')),
                ('highest_score', models.PositiveIntegerField(default=0, verbose_name='Eng yuqori ball (exam mode)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi missiya progressi',
                'verbose_name_plural': 'Foydalanuvchi missiya progresslari',
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="To'plam nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('flashcards', models.ManyToManyField(blank=True, to='Mock.flashcard', verbose_name="To'plamdagi kartochkalar")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Shaxsiy flashcard to'plami",
                'verbose_name_plural': "Shaxsiy flashcard to'plamlari",
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_credits', models.PositiveIntegerField(default=0, verbose_name='Mavjud imtihon kreditlari')),
                ('solution_view_credits', models.PositiveIntegerField(default=0, verbose_name='Mavjud yechim kreditlari')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi balansi',
                'verbose_name_plural': 'Foydalanuvchi balanslari',
            },
        ),
        migrations.CreateModel(
            name='UserAttemptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Bo‘lim balli')),
                ('correct_answers_count', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('incorrect_answers_count', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('remaining_time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qolgan vaqt (soniya)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='Mock.userattempt', verbose_name='Urinish')),
                ('questions', models.ManyToManyField(blank=True, related_name='attempted_in_sections', through='Mock.UserAttemptQuestion', to='Mock.question', verbose_name='Berilgan savollar')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.examsection', verbose_name='Bo‘lim')),
            ],
            options={
                'verbose_name': 'Bo‘lim urinishi',
                'verbose_name_plural': 'Bo‘lim urinishlari',
                'unique_together': {('attempt', 'section')},
            },
        ),
        migrations.AddField(
            model_name='userattemptquestion',
            name='attempt_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.userattemptsection'),
        ),
        migrations.AddField(
            model_name='userattemptquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='UserAnswerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa javob matni')),
                ('is_correct', models.BooleanField(null=True, verbose_name="To'g'riligi")),
                ('answered_at', models.DateTimeField()),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt (soniya)')),
                ('attempt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_answers', to='Mock.userattemptsection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='Mock.answeroption', verbose_name='Tanlangan variantlar')),
            ],
            options={
                'verbose_name': 'Arxivlangan foydalanuvchi javobi',
                'verbose_name_plural': 'Arxivlangan foydalanuvchi javoblari',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ustoz')),
            ],
            options={
                'verbose_name': 'Umumiy mavzu',
                'verbose_name_plural': 'Umumiy mavzular',
                'ordering': ['order'],
                'unique_together': {('name', 'teacher', 'center')},
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ichki mavzu nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='Mock.topic', verbose_name='Umumiy mavzu')),
            ],
            options={
                'verbose_name': 'Ichki mavzu',
                'verbose_name_plural': 'Ichki mavzular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov miqdori")),
                ('is_active', models.BooleanField(default=True, verbose_name="To'lov aktivmi?")),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='Mock.center', verbose_name="O'quv Markazi")),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
        migrations.CreateModel(
            name='QuestionSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yechim uchun maslahat')),
                ('detailed_solution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yechim')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='Mock.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Savol yechimi',
                'verbose_name_plural': 'Savollar yechimi',
            },
        ),
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi')], db_index=True, default='open', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Mock.question', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xabar bergan foydalanuvchi')),
            ],
            options={
                'verbose_name': "Savol bo'yicha shikoyat",
                'verbose_name_plural': "Savollar bo'yicha shikoyatlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='question',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Mock.center', verbose_name='Tegishli Markaz'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.raschdifficultylevel', verbose_name='Qiyinlik darajasi'),
        ),
        migrations.AddField(
            model_name='question',
            name='flashcards',
            field=models.ManyToManyField(blank=True, related_name='questions', to='Mock.flashcard', verbose_name='Savolga oid flashcardlar'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='Mock.question', verbose_name='Asl (ota-ona) savol'),
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Mock.passage', verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='Mock.subtopic', verbose_name='Ichki mavzu'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Mock.tag', verbose_name='Teglar'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('package', 'Paket'), ('subscription', 'Obuna')], max_length=20, verbose_name='Xarid turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Boshlang'ich summa")),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yakuniy summa')),
                ('status', models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('moderation', 'Tekshirilmoqda'), ('completed', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=20, verbose_name='Holati')),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='screenshots/%Y/%m/', verbose_name="To'lov skrinshoti")),
                ('payment_comment', models.TextField(blank=True, null=True, verbose_name="To'lovga izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.exampackage', verbose_name='Paket')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.promocode', verbose_name='Promo kod')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.subscriptionplan', verbose_name='Obuna rejasi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xarid',
                'verbose_name_plural': 'Xaridlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='passage',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='Mock.center', verbose_name='Tegishli Markaz'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilganmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('video', 'Videodars Linki'), ('task', 'Vazifa/Amaliyot Linki'), ('solution_video', 'Yechim Videolinki'), ('solution_file', 'Yechim Fayli Linki/Yuklama'), ('other', 'Boshqa Resurs (PDF, Google Doc va h.k.)')], max_length=20, verbose_name='Resurs turi')),
                ('link', models.URLField(help_text='Video, fayl yoki boshqa materialga tashqi URL manzil.', max_length=500, verbose_name='Resurs linki')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resurs nomi (Masalan: 1-qism)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='Mock.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Dars Resursi',
                'verbose_name_plural': 'Dars Resurslari',
                'ordering': ['resource_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('effort', "Mehnat bo'yicha (ko'p imtihon ishlaganlar)"), ('performance', "Natija bo'yicha (yuqori ball olganlar)")], max_length=20, verbose_name='Leaderboard turi')),
                ('week_number', models.PositiveIntegerField(verbose_name='Hafta raqami')),
                ('score', models.PositiveIntegerField(default=0, verbose_name="Ball yoki ko'rsatkich")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard kirishi',
                'verbose_name_plural': 'Leaderboard kirishlari',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Guruh nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv guruh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Mock.center', verbose_name="O'quv Markazi")),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL, verbose_name="Guruh o'quvchilari")),
                ('teacher', models.ForeignKey(limit_choices_to=models.Q(('role', 'teacher'), ('role', 'center_admin'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='FlashcardReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.PositiveSmallIntegerField(verbose_name='Sifat bahosi (0-5)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'rib chiqish vaqti")),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_log', to='Mock.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard takrorlash logi',
                'verbose_name_plural': 'Flashcard takrorlash loglari',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Flashcard mashg'ulot nomi")),
                ('is_exam_review', models.BooleanField(default=True, verbose_name="Imtihon takrorlash to'plami")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_exams', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('flashcards', models.ManyToManyField(blank=True, related_name='flashcard_exams', to='Mock.flashcard', verbose_name='Flashcardlar')),
                ('source_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_exam', to='Mock.exam', verbose_name='Asosiy imtihon')),
            ],
            options={
                'verbose_name': "Flashcard mashg'uloti",
                'verbose_name_plural': "Flashcard mashg'ulotlari",
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='Mock.center', verbose_name='Tegishli Markaz'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_flashcards', to='Mock.question', verbose_name='Manba-savol'),
        ),
        migrations.CreateModel(
            name='ExamSectionStaticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='Savol tartib raqami')),
                ('exam_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.examsection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question')),
            ],
            options={
                'verbose_name': "Bo'limning statik savoli",
                'verbose_name_plural': "Bo'limning statik savollari",
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.exam')),
                ('exam_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.examsection')),
            ],
            options={
                'verbose_name': 'Imtihon bo‘limi tartibi',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='examsection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsection',
            name='static_questions',
            field=models.ManyToManyField(blank=True, related_name='static_exam_sections', through='Mock.ExamSectionStaticQuestion', to='Mock.question', verbose_name='Statik savollar'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sections',
            field=models.ManyToManyField(related_name='exams', through='Mock.ExamSectionOrder', to='Mock.examsection', verbose_name='Imtihon bo‘limlari'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ustoz'),
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil/Xona')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Mock.course', verbose_name='Kurs')),
                ('related_lesson', models.ForeignKey(help_text="Bu jadval qaysi darsga tegishli ekanligini ko'rsatadi.", on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Mock.lesson', verbose_name="Bog'liq dars")),
            ],
            options={
                'verbose_name': 'Dars Jadvali',
                'verbose_name_plural': 'Dars Jadvali',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ustoz'),
        ),
        migrations.AddField(
            model_name='center',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_centers', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Nishon nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Nishon ikonasi')),
                ('trigger_type', models.CharField(choices=[('exam_completed', 'Imtihon yakunlandi'), ('score_achieved', 'Ball yetkazildi'), ('streak', 'Ketma-ketlik'), ('flashcard_learned', "Flashcard o'rganildi"), ('daily_high_score', 'Eng yaxshi kunlik natija'), ('referral', "Do'stlarni taklif qilish")], help_text='Nishon qachon berilishini tanlang', max_length=50, verbose_name='Meyor turi')),
                ('exam_count', models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Imtihon yakunlandi' tanlangan bo'lsa, shu son yetkazilsa nishon beriladi", verbose_name='Imtihonlar soni (imtihon yakunlash meyorida)')),
                ('min_score', models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Ball yetkazildi' tanlangan bo'lsa, shu balldan yuqori bo'lsa nishon beriladi", verbose_name='Minimal ball (ball yetkazish meyorida)')),
                ('streak_days', models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Ketma-ketlik' tanlangan bo'lsa, shu kun ketma-ket mashq qilinsa nishon beriladi", verbose_name='Ketma-ket kunlar soni (ketma-ketlik meyorida)')),
                ('flashcard_count', models.PositiveIntegerField(blank=True, default=0, help_text="Agar 'Flashcard o'rganildi' tanlangan bo'lsa, shu son o'rganilsa nishon beriladi", verbose_name="Flashcardlar soni (flashcard o'rganish meyorida)")),
                ('daily_min_score', models.PositiveIntegerField(blank=True, default=0, verbose_name='Kunlik minimal ball (eng yaxshi kunlik natija meyorida)')),
                ('referral_count', models.PositiveIntegerField(blank=True, default=0, verbose_name="Taklif qilingan do'stlar soni (referral meyorida)")),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='Mock.center', verbose_name='Tegishli Markaz')),
            ],
            options={
                'verbose_name': 'Nishon (Yutuq)',
                'verbose_name_plural': 'Nishonlar (Yutuqlar)',
            },
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Mock.question', verbose_name='Savol'),
        ),
        migrations.CreateModel(
            name='UserTagPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('incorrect_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan umumiy vaqt (soniya)')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Urinishlar soni')),
                ('average_difficulty', models.FloatField(default=0.0, verbose_name="O'rtacha qiyinlik (Rasch)")),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi urinilgan vaqt')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_performances', to='Mock.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Foydalanuvchi teg/mavzu bo'yicha ko'rsatkichi",
                'verbose_name_plural': "Foydalanuvchi teglar/mavzular bo'yicha ko'rsatkichlari",
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserSolutionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('credit_spent', models.BooleanField(default=False, verbose_name='Kredit sarflandimi?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_views', to='Mock.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ko'rilgan savol yechimi",
                'verbose_name_plural': "Ko'rilgan savol yechimlari",
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_learned', "O'rganilmagan"), ('learning', "O'rganilmoqda"), ('learned', "O'rganilgan")], db_index=True, default='not_learned', max_length=20, verbose_name="O'zlashtirish holati")),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi ko'rilgan vaqt")),
                ('next_review_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Keyingi takrorlash vaqti')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='Osonlik faktori (SM2)')),
                ('review_interval', models.PositiveIntegerField(default=1, verbose_name='Takrorlash intervali (kunda)')),
                ('repetition_count', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli takrorlash soni')),
                ('last_quality_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Oxirgi baho (0-5)')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='Mock.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi flashcard holati (SM2)',
                'verbose_name_plural': 'Foydalanuvchi flashcard holatlari (SM2)',
                'unique_together': {('user', 'flashcard')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='Mock.badge')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='Mock.center', verbose_name='Tegishli Markaz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi nishoni',
                'verbose_name_plural': 'Foydalanuvchi nishonlari',
                'unique_together': {('user', 'badge', 'center')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='userattemptquestion',
            unique_together={('attempt_section', 'question')},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa javob matni')),
                ('is_correct', models.BooleanField(null=True, verbose_name="To'g'riligi")),
                ('is_marked_for_review', models.BooleanField(default=False, verbose_name="Ko'rib chiqish uchun belgilangan")),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt (soniya)')),
                ('attempt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='Mock.userattemptsection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mock.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='Mock.answeroption', verbose_name='Tanlangan variantlar')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
                'unique_together': {('attempt_section', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='Mock_tag_name_7e3a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent'], name='Mock_tag_parent__189b53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'parent', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('name', 'topic', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard_type', 'week_number', '-score'], name='Mock_leader_leaderb_4747ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('user', 'leaderboard_type', 'week_number', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('center', 'teacher', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('english_content', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='examsectionstaticquestion',
            unique_together={('exam_section', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='examsectionorder',
            unique_together={('exam', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('title', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'center')},
        ),
    ]
