# Generated by Django 4.2.1 on 2025-11-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['order_in_cycle', 'day_of_week', 'start_time'], 'verbose_name': 'Takrorlanuvchi Jadval Sloti', 'verbose_name_plural': 'Takrorlanuvchi Jadval Slotlari'},
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['english_content'], 'verbose_name': "Flashcard (lug'at)", 'verbose_name_plural': "Flashcardlar (lug'atlar)"},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='center',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text="Bu o'qituvchilar o'quvchilarni markazga qo'shish so'rovlarini tasdiqlashi mumkin.", related_name='teaching_centers', to=settings.AUTH_USER_MODEL, verbose_name="Markaz O'qituvchilari"),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], default=1, verbose_name='Hafta kuni'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='is_start_slot',
            field=models.BooleanField(default=False, help_text='Agar Kurs yangi guruh uchun boshlansa, Lesson 1 aynan shu slotga moslanadi.', verbose_name="Boshlang'ich slot"),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='order_in_cycle',
            field=models.PositiveIntegerField(default=1, help_text="Bu slot haftalik darslar siklida nechanchi o'rinda turishini ko'rsatadi (1 dan boshlab).", verbose_name='Haftalik sikldagi tartibi'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='flashcards', to='Mock.tag', verbose_name='Tegishli Taglar/Mavzular'),
        ),
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text="Guruh bog'langan kurslar ro'yxati.", related_name='groups_in_course', to='Mock.course', verbose_name='Kurslar'),
        ),
        migrations.AddField(
            model_name='raschdifficultylevel',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mock.center', verbose_name='Markaz'),
        ),
        migrations.AddField(
            model_name='useranswerarchive',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_answers_by_center', to='Mock.center', verbose_name='Tegishli Markaz'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_attempts', to='Mock.center', verbose_name='Tegishli Markaz'),
        ),
        migrations.AddField(
            model_name='userattemptsection',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_section_attempts', to='Mock.center', verbose_name='Tegishli Markaz'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_ever_active',
            field=models.BooleanField(default=False, editable=False, verbose_name="Avval faol bo'lganmi"),
        ),
        migrations.AlterField(
            model_name='center',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_centers', to=settings.AUTH_USER_MODEL, verbose_name="Bosh O'qituvchi / Ega"),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='Mock.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='examsectionorder',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examsectionorder', to='Mock.exam'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='context_sentence',
            field=models.TextField(blank=True, null=True, verbose_name='Kontekst (gap) (HTML)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='english_content',
            field=models.TextField(help_text="CKEditor kodi bu yerda to'g'ridan-to'g'ri bo'lishi kerak", verbose_name='Inglizcha kontent (HTML)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='uzbek_meaning',
            field=models.TextField(verbose_name="O'zbekcha ma'nosi (HTML)"),
        ),
        migrations.AlterField(
            model_name='group',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Mock.center'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchilar"),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'center_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=models.TextField(verbose_name='Matn (HTML)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Foiz chegirmasi uchun, masalan, 10% uchun 10 kiriting (0-100 oralig'ida bo'lishi kerak)", null=True, verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='Mock.exam', verbose_name='Imtihon'),
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('course', 'day_of_week', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='related_lesson',
        ),
    ]
