# Generated by Django 4.2.1 on 2025-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0002_alter_courseschedule_options_alter_flashcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('center_admin', 'Markaz Admini'), ('admin', 'Admin')], default='student', max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
