# Generated by Django 4.2.1 on 2025-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('center_admin', 'Markaz Admini'), ('admin', 'Platforma Super Admini')], default='student', max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
