# Generated by Django 4.2.1 on 2025-12-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_at', models.DateTimeField(auto_now_add=True, verbose_name='Kalibratsiya sanasi')),
                ('response_count_used', models.PositiveIntegerField(verbose_name='Ishlatilgan javoblar soni')),
                ('difficulty', models.FloatField(verbose_name='Qiyinlik (b)')),
                ('discrimination', models.FloatField(default=1.0, verbose_name='Farqlash (a)')),
                ('guessing', models.FloatField(default=0.25, verbose_name='Taxmin (c)')),
                ('method', models.CharField(choices=[('rasch_simple', 'Oddiy Rasch'), ('2pl', '2PL Model'), ('3pl', '3PL Model')], default='rasch_simple', max_length=20, verbose_name='Usul')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='Mock.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Savol kalibratsiyasi',
                'verbose_name_plural': 'Savollar kalibratsiyasi',
                'ordering': ['-calibrated_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='current_calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_question', to='Mock.questioncalibration', verbose_name='Hozirgi kalibratsiya'),
        ),
    ]
