# Generated by Django 4.2.1 on 2025-12-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0005_questioncalibration_question_current_calibration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raschdifficultylevel',
            options={'verbose_name': 'Rasch darajasi', 'verbose_name_plural': 'Rasch darajalari'},
        ),
        migrations.AlterField(
            model_name='raschdifficultylevel',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rasch_levels', to='Mock.center', verbose_name='Markaz'),
        ),
        migrations.AlterField(
            model_name='raschdifficultylevel',
            name='max_difficulty',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='raschdifficultylevel',
            name='min_difficulty',
            field=models.FloatField(default=-3.0),
        ),
        migrations.AlterField(
            model_name='raschdifficultylevel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Daraja nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='raschdifficultylevel',
            unique_together={('name', 'center')},
        ),
    ]
