# Generated by Django 4.2.1 on 2025-12-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0006_alter_raschdifficultylevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='related_exam',
            field=models.ForeignKey(blank=True, help_text="Bu darsga test biriktirilishi shart emas. Agar biriktirilsa, keyingi darsga o'tish uchun talab etiladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_linked', to='Mock.exam', verbose_name='Mavzu testi'),
        ),
    ]
