# Generated by Django 4.2.1 on 2025-12-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0007_alter_lesson_related_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'rilgan vaqt")),
                ('lesson_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='Mock.lessonresource', verbose_name='Resurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_views', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Foydalanuvchi Resurs Ko'ruvchi",
                'verbose_name_plural': "Foydalanuvchi Resurs Ko'ruvchilari",
                'unique_together': {('user', 'lesson_resource')},
            },
        ),
    ]
