# Generated by Django 4.2.1 on 2025-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0008_userresourceview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Kurs rasmi (bosh rasm)'),
        ),
    ]
