# Generated by Django 4.2.1 on 2025-12-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mock', '0009_course_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mock.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('package', 'Paket'), ('subscription', 'Obuna'), ('course', 'Kurs')], max_length=20, verbose_name='Xarid turi'),
        ),
    ]
